<template>
  <v-sheet color="#F7F0F0">
    <v-container fluid class="pa-10 pa-md-16">

      <div class="d-flex align-center ga-3 mb-3">
        <v-divider length="22" color="#48A111" thickness="2" />
        <span style="font-family:'JetBrains Mono',monospace;font-size:11px;letter-spacing:0.16em;color:#48A111;text-transform:uppercase;">
          C · Economic Impact
        </span>
      </div>
      <v-row align="end" class="mb-10">
        <v-col cols="12" md="6">
          <div style="font-family:'Instrument Serif',serif;font-size:clamp(1.8rem,2.8vw,2.5rem);color:#111810;letter-spacing:-0.025em;line-height:1.1;">
            Regional Economic Contribution
          </div>
        </v-col>
        <v-col cols="12" md="5" offset-md="1">
          <p style="font-size:14px;color:#6B7B6A;line-height:1.72;margin:0;">
            TBI tracks economic indicators aligned with national innovation targets —
            jobs created, MSMEs supported, and industry collaborations. Metrics are
            updated per annual report cycle.
          </p>
        </v-col>
      </v-row>

      <!-- Impact metrics -->
      <v-row class="mb-8">
        <v-col v-for="m in economicMetrics" :key="m.label" cols="12" sm="6" md="4">
          <v-card color="white" rounded="xl" elevation="0" border style="border-color:#E8E0D8;height:100%;">
            <v-card-text class="pa-7">
              <div class="d-flex justify-space-between align-start mb-4">
                <v-avatar :color="m.color" variant="tonal" rounded="lg" size="44">
                  <v-icon :icon="m.icon" size="20" :color="m.color" />
                </v-avatar>
                <v-chip :color="m.color" variant="tonal" size="x-small"
                  style="font-family:'JetBrains Mono',monospace;font-size:9px;letter-spacing:0.08em;text-transform:uppercase;">
                  {{ m.category }}
                </v-chip>
              </div>
              <div style="font-family:'Instrument Serif',serif;font-size:2.75rem;color:#111810;letter-spacing:-0.05em;line-height:1;margin-bottom:6px;">{{ m.val }}</div>
              <div style="font-weight:700;font-size:14px;color:#111810;margin-bottom:6px;">{{ m.label }}</div>
              <p style="font-size:13px;color:#6B7B6A;line-height:1.65;margin-bottom:14px;">{{ m.note }}</p>
              <v-progress-linear :model-value="m.progress" :color="m.color" bg-color="#F0EAE0" height="3" rounded />
              <div style="font-family:'JetBrains Mono',monospace;font-size:9px;color:#9eaa9c;margin-top:6px;letter-spacing:0.06em;">{{ m.target }}</div>
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>

      <!-- SDG alignment -->
      <v-card color="#111810" rounded="xl" elevation="0">
        <v-card-text class="pa-8">
          <v-row align="center">
            <v-col cols="12" md="4">
              <div style="font-family:'Instrument Serif',serif;font-size:1.25rem;color:#fff;margin-bottom:8px;">SDG Alignment</div>
              <p style="font-size:13px;color:rgba(255,255,255,0.45);line-height:1.7;margin:0;">
                TBI's commercialization and incubation work directly supports
                the Philippines' Ambisyon 2040 and the following Sustainable
                Development Goals.
              </p>
            </v-col>
            <v-col cols="12" md="8">
              <div class="d-flex flex-wrap ga-3">
                <v-chip v-for="sdg in sdgGoals" :key="sdg.num"
                  :color="sdg.color" variant="flat" size="small"
                  style="font-family:'JetBrains Mono',monospace;font-size:10px;letter-spacing:0.06em;font-weight:700;">
                  SDG {{ sdg.num }}: {{ sdg.label }}
                </v-chip>
              </div>
            </v-col>
          </v-row>
        </v-card-text>
      </v-card>

    </v-container>
  </v-sheet>
</template>

<script setup>
const economicMetrics = [
  { icon: 'mdi-account-hard-hat-outline',  color: '#25671E', val: 'TBD',  label: 'Direct Jobs Created',      note: 'Jobs generated by incubated startups and spin-offs per annual tracking cycle.',                   category: 'Employment',    progress: 0,   target: 'Updated per Annual Report'    },
  { icon: 'mdi-store-outline',             color: '#48A111', val: 'TBD',  label: 'Local MSMEs Supported',    note: 'MSMEs onboarded via technology matching protocol — must align with CSU R&D outputs.',             category: 'MSME',          progress: 0,   target: 'Updated per Annual Report'    },
  { icon: 'mdi-handshake-outline',         color: '#e09000', val: '5+',   label: 'Industry Collaborations',  note: 'Annual target: at least 5 strategic partnerships with government, industry, and academia.',        category: 'Target',        progress: 55,  target: 'Annual Target per Objectives' },
  { icon: 'mdi-currency-php',              color: '#25671E', val: '3%',   label: 'Royalty Rate',             note: 'TBI is entitled to 3% royalty from net annual revenue of incubatees per Incubation Agreement.',   category: 'Revenue Model', progress: 100, target: 'Per Incubation Agreement'    },
  { icon: 'mdi-map-marker-radius-outline', color: '#48A111', val: '4',    label: 'LGU Technology Adoptions', note: 'MapX adopted by Butuan, Mainit, Oroquieta City, and Mambajao Camiguin — primary commercial output.',category: 'Adoption',      progress: 80,  target: 'MapX Platform Adoptions'     },
  { icon: 'mdi-account-group-outline',     color: '#25671E', val: '30%+', label: 'Inclusivity Target',       note: 'At least 30% of incubated startups must be led by women, youth, or underrepresented communities.', category: 'Inclusivity',   progress: 30,  target: 'Per TBI Objectives'           },
]

const sdgGoals = [
  { num: 1,  label: 'No Poverty',            color: '#E5243B' },
  { num: 2,  label: 'Zero Hunger',           color: '#DDA63A' },
  { num: 8,  label: 'Decent Work',           color: '#A21942' },
  { num: 9,  label: 'Industry & Innovation', color: '#FD6925' },
  { num: 10, label: 'Reduced Inequalities',  color: '#DD1367' },
  { num: 17, label: 'Partnerships',          color: '#19486A' },
]
</script>